#!/usr/bin/python
import os
import re
import json
import sys, getopt
import argparse

# Script used to generate required data for GoogleDoc worksheet. This requires the intermediate song report generated by Robert (contains mapping information between legacy ICGC analysis ID and ARGO analysis IDs) and the summary file after processing.

## Example inputs:
## summary_file: https://raw.githubusercontent.com/icgc-argo/argo-meta/master/icgc_song_payloads/PACA-CA/WGS/PACA-CA_WGS_batch1_summary.tsv
## intermediate song mapping file: https://raw.githubusercontent.com/icgc-argo/argo-meta/master/icgc_song_payloads/PACA-CA/WGS/intermediate-song-rdpc-collab-report.PACA-CA.WGS.batch1.json
## output_file: worksheet.tsv
##
## Copy contents of worksheet.tsv into main GoogleDoc worksheet


parser = argparse.ArgumentParser()
parser.add_argument("-s", "-summary_file", dest="summary_file", required=True)
parser.add_argument("-i", "-intermediate_song_file", dest="intermediate_song_file", required=True)
parser.add_argument("-o", "-out_file", dest="out_file", required=True)
args = parser.parse_args()

intermediateReport = args.intermediate_song_file

summaryFile = open(args.summary_file, "r")
outFile = open(args.out_file, "w")
outFile.write("submitter_donor_id\tsubmitter_sample_id\ttumour_normal_designation\tsequencing_strategy\tdonor_id\tsample_id\tstudy_id\tanalysis_id\n")
completed = {}



def get_analysisId_mapping():
   mapping = {}
   mapping_file = open("analysis_id_mapping.tsv", "w")
   report = json.load(open(intermediateReport, "r"))
   for payload in report["success"]:
      legacyAnalysisIds = payload["legacyAnalysisIds"]
      for legacy_id in legacyAnalysisIds:
         mapping[legacy_id] = payload["targetAnalysisId"]

   for legacy_id in mapping:
      mapping_file.write("%s\t%s\n"%(legacy_id, mapping[legacy_id]))
   mapping_file.close()
   return mapping

mapping = get_analysisId_mapping()
contents = summaryFile.readlines()
contents.pop(0)
for line in contents:
   line = line.rstrip("\n")
   data = line.split("\t")
   icgc_analysis_id = data[7]
   if icgc_analysis_id in mapping and icgc_analysis_id not in completed:
      print("Processing icgc_analysis_id=%s"%icgc_analysis_id)
      argo_analysis_id = mapping[icgc_analysis_id]
      dcc_donor_id = data[8]
      submitter_donor_id = data[9]
      specimen_type = data[12]
      dcc_sample_id = data[13]
      submitter_sample_id = data[14]
      sequencing_strategy = data[16]
      study_id = data[0]
      if re.search("tumour", specimen_type, re.IGNORECASE):
         tumour_normal_designation = "tumour"
      if re.search("normal", specimen_type, re.IGNORECASE):
         tumour_normal_designation = "normal"

      outFile.write("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n"%(submitter_donor_id, submitter_sample_id, tumour_normal_designation, sequencing_strategy, dcc_donor_id, dcc_sample_id, study_id, argo_analysis_id))
   completed[icgc_analysis_id] = argo_analysis_id 
outFile.close()
