{
  "name": "DO35144.PACA-CA.WGS.tumour",
  "exp_tsv": "[exp.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO35144/PCSI_0044_Pa_P.tumour/experiment.tsv",
  "file_tsv": "[file.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO35144/PCSI_0044_Pa_P.tumour/file.tsv",
  "seq_files": [],
  "rg_tsv": "[read_group.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO35144/PCSI_0044_Pa_P.tumour/read_group.tsv"
}
