{
  "name": "DO51526.PACA-CA.WGS.normal",
  "exp_tsv": "[exp.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO51526/PCSI_0309_Ly_R.normal/experiment.tsv",
  "file_tsv": "[file.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO51526/PCSI_0309_Ly_R.normal/file.tsv",
  "seq_files": [],
  "rg_tsv": "[read_group.tsv]https://github.com/icgc-argo/argo-meta/blob/master/dna-seq-alignment/tests/WGS/PACA-CA/DO51526/PCSI_0309_Ly_R.normal/read_group.tsv"
}
