{
  "name": "DO224740.PACA-CA.WGS.tumour",
  "exp_tsv": "[exp.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO224740/PCSI_0594_Pa_P_526.tumour/experiment.tsv",
  "file_tsv": "[file.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO224740/PCSI_0594_Pa_P_526.tumour/file.tsv",
  "seq_files": [],
  "rg_tsv": "[read_group.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO224740/PCSI_0594_Pa_P_526.tumour/read_group.tsv",
  "ref_genome": "/home/ubuntu/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa",
  "ref_genome_gz": "/home/ubuntu/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa.gz"
}
