{
  "name": "DO227604.PACA-CA.WGS.tumour",
  "exp_tsv": "[exp.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO227604/PCSI_0518_Pa_P_526.tumour/experiment.tsv",
  "file_tsv": "[file.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO227604/PCSI_0518_Pa_P_526.tumour/file.tsv",
  "seq_files": [],
  "rg_tsv": "[read_group.tsv]https://raw.githubusercontent.com/icgc-argo/argo-meta/master/dna-seq-alignment/tests/WGS/PACA-CA/DO227604/PCSI_0518_Pa_P_526.tumour/read_group.tsv"
}
